Test volume clerk client
Enstore-org/enstore pull request #130
Opened 2023-06-23 20:02 UTC by dbox-fnal

2023-07-12 19:30 UTC, renbauer-fnal requested changes

2023-07-12 19:30 UTC, renbauer-fnal commented on src/tests/test_volume_clerk_client.py
> +        c3 = volume_clerk_client.capacity_str(inp)
Can we add a test case for KB here and one that sends a negative?

2023-07-12 19:30 UTC, renbauer-fnal commented on src/tests/test_volume_clerk_client.py
> +    def test_my_atol(self):
Do we know what this function (my_atol) actually does? It appears to parse units to standardize values but what does "atol" mean? Why isn't it called my_size_in_bytes?

2023-07-12 19:30 UTC, renbauer-fnal commented on src/tests/test_volume_clerk_client.py
> +    def test_set_system_migrated(self):
Man, all these are almost identical. Can we simplify these functions to be something like:
```
def assert_generates_work_ticket(work_str, test_func, extra_items={}):
  expected_work_ticket = {'work': work_str,
                          'external_label': 'external_label'} + extra_items
  self.sent_msg.reset_mock()
  test_func()
  generated_work_ticket = self.sent_msg.mock_calls[0][1][0]
  self.assertEqual(generated_work_ticket, expected_work_ticket)

def test_set_system_migrated(self):
  assert_generates_work_ticket('set_system_migrates', 
     lambda: self.vcc.set_system_migrated('external_label'))
```

Maybe there is a cleaner way than passing lambdas but my kwargs-fu is not up to it atm

2023-07-12 19:30 UTC, renbauer-fnal commented on src/tests/test_volume_clerk_client.py
> +                        arglebargle = """{'not': None, 'work': 'get_vols3', 'key': None, 'in_state': 'noaccess'}"""
Nice var name, but is this used?

2023-07-12 19:30 UTC, renbauer-fnal commented on src/tests/test_volume_clerk_client.py
> +                        self.vci.labels = 0
Can we move these resets to the bottom of the test cases above, like you are doing later in these cases?

2023-07-18 00:12 UTC, dbox-fnal commented on src/tests/test_volume_clerk_client.py
> +                        self.vci.labels = 0
Done.

2023-07-18 00:14 UTC, dbox-fnal commented on src/tests/test_volume_clerk_client.py
> +                        arglebargle = """{'not': None, 'work': 'get_vols3', 'key': None, 'in_state': 'noaccess'}"""
Must be a remnant from an earlier test approach, removing does not affect the test

2023-07-18 00:28 UTC, dbox-fnal commented on src/tests/test_volume_clerk_client.py
> +    def test_set_system_migrated(self):
There are most likely ways to simplify this,  I will experiment on other repetitive client tests.  This one is done and works so I would prefer to leave it as is.  The test of do_work() lower down is also repetitive and ugly and I would like even more to come up with something parameterized for it.

2023-07-18 00:32 UTC, dbox-fnal commented on src/tests/test_volume_clerk_client.py
> +    def test_my_atol(self):
My guess is named after atol(3) in the standard C library.

2023-07-18 00:54 UTC, dbox-fnal commented
reviewer suggestions implemented, waiting for approval

2023-07-24 18:14 UTC, renbauer-fnal approved these changes

2023-07-24 18:15 UTC, merged