Add pytests for movcmd_mc module
Enstore-org/enstore pull request #33
Opened 2022-01-11 03:06 UTC by renbauer-fnal

Recreated to use only the Docker build workflow

2022-01-20 18:10 UTC, ddbox commented
Review comments:
I was able to run the tests successfully, they appear to have good coverage.

My only suggestion for improvements is a  stylistic one.  The Pep8 style guide, which as AFAIK is the default standard, recommends 4 spaces for indentations instead of 2.   The 'autopep8' utility, which can be installed via pip, is my preferred way to change python whitespace issues but YMMV.

After the above change this branch is OK to merge.

2022-01-20 18:16 UTC, ddbox requested changes
I left review comments in what appears to be the wrong window, I am still learning the github UI.  The tabs were replaced with spaces, which is good.  Please change the indentation from 2 spaces to the Pep8 standard of 4 spaces.  After that OK to merge.

2022-01-21 16:40 UTC, renbauer-fnal commented
Jeez, using 4 spaces to indent makes me feel icky. We're really supposed to have lines that start with 20-24+ spaces and still keep all of them under 80 (79) characters? This feels like it's just promoting non-descriptive variable names. I agree trying to adhere to the standard is the way to go, though, I'll standardize here.

2022-01-21 17:11 UTC, ddbox approved these changes

2022-01-21 17:11 UTC, merged